spring:
  jpa:
    properties:
      hibernate:
        show-sql: true
        format_sql: true
        use_sql_comments: true
        generate_statistics: true
    #defer-datasource-initialization: true 설정 => data.sql 초기화 필요시 사용
    #    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
  h2:
    console:
      settings:
        web-allow-others: true
      enabled: true
      # 시스템 설정이라 바꿔줘야함
  jackson:
    serialization:
      FAIL_ON_EMPTY_BEANS: false

  config:
      activate:
        on-profile: release
# 배포 서버용 세팅
server:
  port: 3000

# 환경변수 설정으로 세팅
jwt:
  secret: ${JWT_SECRET_KEY} #base64 32byte
  token:
    refresh-expires: 7200000 #2시간
    access-expires: 7200000
# S3
cloud:
  aws:
    credentials:
      access-key: ${S3_SHOUXKREAM_ACCESS_KEY}
      secret-key: ${S3_SHOUXKREAM_SECRET_KEY}
    s3:
      bucket: ${S3_SHOUXKREAM_BUCKET}
    region:
      static: ap-northeast-2
    stack:
      auto: false